Курсовая/myshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

Курсовая/myshop/myshop/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from shop import urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    path('cart/', include(('cart.urls','cart' ), namespace='cart')),
    path('orders/', include(('orders.urls','orders'), namespace='orders')),
    path('', include(('shop.urls', 'shop'), namespace='shop')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Курсовая/myshop/orders/urls.py
from django.urls import path
from . import views

urlpatterns = [
 path('create/', views.order_create, name='order_create'),
]

Курсовая/myshop/shop/urls.py
from django.urls import path
from . import views

app_name='shop'

urlpatterns = [
    path('', views.shop, name='shop'),
    path('<int:id>/<slug:slug>/' , views.product_detail, name='product_detail'),
    path('<slug:category_slug>/' , views.category_slug, name='category_slug'),
] 

Курсовая/myshop/cart/models.py
from django.db import models

# Create your models here.

Курсовая/myshop/orders/models.py
from django.db import models
from shop.models import Product

class Order(models.Model):
    Имя = models.CharField(max_length=50)
    Фамилия = models.CharField(max_length=50)
    Эл_почта = models.EmailField()
    Адрес = models.CharField(max_length=250)
    Индекс = models.CharField(max_length=20)
    Город = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    paid = models.BooleanField(default=False)
    
    class Meta:
        ordering = ('-created',)
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'
    
    def __str__(self):
        return 'Order {}'.format(self.id)
    
    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)
 
    def __str__(self):
        return '{}'.format(self.id)
 
    def get_cost(self):
        return self.price * self.quantity

Курсовая/myshop/shop/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    def get_absolute_url(self):
        return f'/{self.slug}/'
    
    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
    
    def __str__(self):
            return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
        
    def __str__(self):
        return self.name

Курсовая/myshop/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label="Количество")
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput )
    

Курсовая/myshop/orders/forms.py
from django import forms
from .models import Order

class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['Имя', 'Фамилия', 'Эл_почта',
    'Адрес', 'Индекс', 'Город']

Курсовая/myshop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


#чтобы разрешить только POST запросы, используем декоратор require_Post
@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    #Если форма является валидной, мы получим код, введенный
    # пользователем из формы cleaned_data
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

Курсовая/myshop/orders/views.py
from django.shortcuts import render
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart

def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order, product=item['product'], price=item['price'], quantity=item['quantity'])
            # очистка корзины
            cart.clear()
            return render(request, 'orders/order/created.html', {'order': order})
    else:
        form = OrderCreateForm()
    return render(request, 'orders/order/create.html',{'cart': cart, 'form': form})

Курсовая/myshop/shop/views.py
from django.shortcuts import render
from .models import Category, Product
from django.http import Http404
from cart.forms import CartAddProductForm
from django.shortcuts import get_object_or_404

def shop(request):
    return render(request, 'base.html', {"contents": Product.objects.all(), "categories":Category.objects.all()})

def product_list(request, category_slug=None):
    category=None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category=get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'product/list.html',
{
    'category':category,
    'categories': categories,
    'products':products,
})

def detail_product(request, detail):
    try:
        post = Product.objects.get(id=detail)
        return render(request, 'product/detail.html', {"product": post})
    except Product.DoesNotExist:
        raise Http404


def category_slug(request, category_slug):
    for categorys in Category.objects.all():
        if str(category_slug) == str(categorys.slug):
            return render(request, 'base.html', {"contents": Product.objects.filter(category_id=categorys.id), "categories":Category.objects.all()})
        

def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'product/detail.html', {'product': product, 'cart_product_form': cart_product_form})

    

Курсовая/myshop/cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
Your shopping cart
{% endblock %}
{% block categories %}
{% endblock %}
{% block content %}
<div class="cart_table">
<h1 style="text-align: center;">Твоя корзина</h1>
<table class="cart">
    <col style="width:20%; text-align: center;">
	<col style="width:10%">
	<col style="width:10%">
    <col style="width:10%">
    <col style="width:20%">
    <col style="width:20%">
    <thead>
        <tr>
            <th></th>
            <th>Название</th>
            <th>Количество</th>
            <th></th>
            <th>Цена 1шт</th>
            <th>Цена</th>
        </tr>
    </thead>
    <tbody>
        {% for item in cart %}
        {% with product=item.product %}
        <tr>
            <td class="product-img" >
                <a href="{{ product.get_absolute_url }}" > 
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
                </a>
            </td>
            <td class="total">{{ product.name }} {{ item.name }}</td>
            <td class="total">{{ item.quantity }}</td>
            <td><a href="{% url  'cart:cart_remove' product.id%}" class="category_cart">Удалить</a></td>
            <td class="num">{{ item.price }} руб</td>
            <td class="num">{{ item.total_price }} руб</td>
        </tr>
        
        {% endwith %}
        {% endfor %}
        
        <tr >
            <td colspan="4"></td>
            <td class="total">Сумма покупки:</td>
            <td class="num">{{ cart.get_total_price }} руб</td>
        </tr>
    </tbody>
</table>
<div style="text-align: center; margin:20px;">
    <a href="/" class="category_cart_1"> Вернуться на главную страницу </a>
    <a href="{% url 'orders:order_create' %}" class="category_cart_1"> Оформить заказ </a>
</div>
</div>
{% endblock %}

Курсовая/myshop/orders/templates/orders/order/create.html
{% extends "shop/base.html" %}
{% block title %}Checkout{% endblock %}
{% block categories %}
<div style="margin: 10px; background-color: #c0a97a9f; text-align:center; position:absolute; width: 30%; border:2px ;">
<h3 >Твой заказ</h3>
    <ul>
        {% for item in cart %}
        <p>
            {{ item.quantity }}x {{ item.product.name }}
            <span>{{ item.total_price }} руб</span>
        </p>
        {% endfor %}
        <h3>Итого: {{ cart.get_total_price }} руб</h3>
    </ul>
</div>
{% endblock %}
{% block content %}
<div style="text-align:left; position:absolute; width:30%; left: 20%; font-size: 25px;">
<form action="." method="post" class="order-form">
    {{ form.as_p }}
    <p><input type="submit" value="Сделать заказ"></p>
    {% csrf_token %}
</form>
</div>
{% endblock %}

Курсовая/myshop/orders/templates/orders/order/created.html
{% extends "shop/base.html" %}
{% block title %}Thank you{% endblock %}
{% block categories %}
{% endblock %}
{% block content %}
<h1>Спасибо</h1>
<p>Ваш заказ создан. Ваш номер заказа: 
    <strong>{{ order.id }}</strong>.
</p>
{% endblock %}

Курсовая/myshop/shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>{% block title %}My shop{% endblock %}</title>
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>

<body>
    <div id="header">
        <a href="/" class="logo">ShopForYou</a>
    </div>
    <hr id="subheader">
    <p class="cart_base">
        {% with total_items=cart|length %}
        {% if cart|length > 0 %}
       
        <a href="{% url 'cart:cart_detail' %}" class="logo">
            Корзина:
            {{ total_items }}
        </a>
        ({{ cart.get_total_price }} руб)
        {% else %}
        Корзина пуста
        {% endif %}
        {% endwith %}
    </p>
    <hr>
    {% block categories %}
    <div id="categories">
        <p style="text-align: center;">Категории</p>
        <a href="/" class="category" style="text-align: center;"> Все категории </a>
        {% for category in categories %}
        <p>
            <a href="/{{ category.slug }}/" class="category"> {{category.name }} </a>
        </p>
        {% endfor %}
    </div>
    {% endblock %}
    <div id="content">
        {% block content %}
        {% for content in contents %}
        <div class="product-wrap">
            <div class="product-item">
                <img
                    src="{% if content.image %}{{ content.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
                <div class="product-buttons">
                    <a href="/{{ content.id }}/{{ content.slug }}/" class="button">В корзину</a>
                </div>
            </div>
            <div class="product-title">
                <a href="/{{ content.id }}/{{ content.slug }}/">{{content.name}}</a>
                <span class="product-price">{{content.price}} руб</span>
            </div>
        </div>
        {% endfor %}
        {% endblock %}
    </div>
</body>

</html>

Курсовая/myshop/shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block categories %}
<div class="product-img">
    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
</div>
{% endblock %}
{% block title %}
{% if category %}
{{ category.title }}
{% else %}Products
{% endif %}
{% endblock %}
{% block content %}
<div class="product-detail">
    <h1>{{ product.name }}</h1>
    <h3><a href="{{ product.category.get_absolute_url }}" class="category" >{{ product.category.name }}</a></h3>
    <div ><h2 class="price">{{ product.price }} руб</h2>
        <p class="description" >{{ product.description|linebreaks }}</p></div>

        <form action="{% url 'cart:cart_add' product.id %}" method="post" style="font-weight: bolder;">
         {{ cart_product_form }}
         {% csrf_token %}
         <input type="submit" value="Добавить в корзину">
        </form>
    
</div>
{% endblock %}

Курсовая/myshop/shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
<div id="sidebar">
    <h3>Categories</h3>
    <ul>
        <li {% if not category %}class="selected" {% endif %}>
            <a href="{% url 'shop:product_list' %}">All</a>
        </li>
        {% for c in categories %}
        <li  class="selected">
            <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>
        {% endfor %}
    </ul>
</div>
<div id="main" class="product-list">
    <h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
    {% for product in products %}
    <div class="item">
        <a href="{{ product.get_absolute_url }}">
            <img src="{% if product.image %}{{ product.image.url }}{% else
%}{% static 'img/no_image.png' %}{% endif %}">
        </a>
        <a href="{{ product.get_absolute_url }}">{{ product.name
            }}</a><br>
        ${{ product.price }}
    </div>
    {% endfor %}
</div>
{% endblock %}